import { Metadata } from "next"

export const metadata:Metadata = {
  title:{
    default:"Nextjs",
    template:"%s | Coder"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor:'black',color:'white',padding:'1.5rem'}}>
          Header
        </header>
        {children}
        <footer style={{backgroundColor:'black',color:'white',padding:'1.5rem'}}>
          footer
        </footer>
      </body>
    </html>
  )
}
