export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
  };

  export default function AuthLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return (
      <>
        {children}
        <h1 style={{ backgroundColor: "gold" }}>auth</h1>
      </>
    );
  }
