"use client"


import Link from "next/link";
import { useParams, usePathname } from "next/navigation";
import { useState } from "react";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

const navigation = [
  { name: "login", href: "/login" },
  { name: "Register", href: "/register" },
  { name: "forget Password", href: "/forget-password" },
];

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [input,setInput] = useState('')
  const pathName = usePathname();
  return (
    <>
      {children}
      <input value={input} onChange={(e)=>setInput(e.target.value)}/>
      <h1 style={{ backgroundColor: "gold" }}>auth</h1>
      {navigation.map((nav) => {
        const isActive = pathName.startsWith(nav.href);

        return (
          <Link
            href={nav.href}
            style={{ color: isActive ? "orange" : "blue", padding: "1rem" }}
          >
            {nav.name}
          </Link>
        );
      })}
    </>
  );
}
